GET https://animeapi-qqzb.onrender.com/animeList
###
GET http://localhost:8000/api/animeList/1

###
PATCH http://localhost:8000/api/animeList/3
Content-Type: application/json

{
    "opening": "https://www.youtube.com/watch?v=RS94j08yIHs&list=RDpyvpg2mK5Do&index=2"
}

### Fetch Data
POST http://localhost:8000/api/fetchList