GET https://animeapi-qqzb.onrender.com/animeList
###
GET http://localhost:8000/animeList

###
POST http://localhost:8000/api/animeList
Content-Type: application/json

{
    "title": "Dr. Stone: New World",
    "image":"https://cdn.myanimelist.net/images/anime/1794/135148.webp",
    "studio": "TMS Entertainment",
    "source": "Manga",
    "theme" : "Time Travel",
    "score": 8.32,
    "genre": ["action", "comedy"]
}

###
GET https://api.myanimelist.net/v2/anime/season/2023/spring