GET https://animeapi-qqzb.onrender.com/api/animeList
###
GET http://localhost:8000/api/anime

###
PATCH http://localhost:8000/api/animeList/2
Content-Type: application/json

{
    
}

###
GET https://api.myanimelist.net/v2/anime/season/2023/spring